name: Produce Artifacts
on: 
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Caching dependencies 
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: dep-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Run the test cases
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{steps.publish.outputs.script-file}}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Caching dependencies 
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: dep-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Build the app
        run: npm run build
      - name: Publish Js file
        id: publish
        run: find dist/assets/*.js -type f -execdir echo "script-file={}" >> $GITHUB_OUTPUT ";"
      - name: Store/upload the produced artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Confirm the output of dist-files
        run: ls
      - name: Output JS file name
        run: echo "${{needs.build.outputs.script-file}}"
      - name: Deploy the app
        run: echo "Deploying . . ." 